Add controllers
AlexanderSharygin/java-shareit pull request #1
Opened 2022-11-27 12:50 UTC by AlexanderSharygin

2022-11-29 18:08 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2022-11-29 18:08 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @NonNull
Аннотации валидации понадобятся только у dto классов

2022-11-29 18:08 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/ItemDaoImpl.java
> +    private final HashMap<Long, Item> items = new HashMap<>();
В качестве типа переменной используем интерфейс!

2022-11-29 18:08 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/ItemDaoImpl.java
> +                .findFirst().get();
Внимание! К методу `get()` обратились без проверки... Сначала у тебя Optional, там может и не быть ничего, это надо проверить...

2022-11-29 18:08 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +    public UserDto findById(long id) {
Давай глагол `find` использовать в репозиториях.
А в сервисах `get`-> `gatAll` / `getById`

2022-11-30 17:00 UTC, AlexanderSharygin commented on src/main/java/ru/practicum/shareit/exception/model/ValidationException.java
> +public class ValidationException extends RuntimeException {
fixed

2022-11-30 17:02 UTC, AlexanderSharygin commented on src/main/java/ru/practicum/shareit/exception/model/NotExistException.java
> +public class NotExistException extends RuntimeException {
fixed

2022-11-30 17:03 UTC, AlexanderSharygin commented on src/main/java/ru/practicum/shareit/exception/model/AlreadyExistException.java
> +public class AlreadyExistException extends RuntimeException {
fixed

2022-11-30 17:08 UTC, AlexanderSharygin commented on src/main/java/ru/practicum/shareit/exception/controller/ExceptionApiHandler.java
> +        log.warn(e.getMessage());
fixed

2022-11-30 17:10 UTC, AlexanderSharygin commented on src/main/java/ru/practicum/shareit/item/ItemDaoImpl.java
> +        return null;
fixed

2022-11-30 17:14 UTC, AlexanderSharygin commented on pom.xml
> +							<version>10.3.1</version>
fixed

2022-11-30 17:16 UTC, AlexanderSharygin commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @NonNull
fixed

2022-11-30 17:18 UTC, AlexanderSharygin commented on src/main/java/ru/practicum/shareit/item/ItemDaoImpl.java
> +    private final HashMap<Long, Item> items = new HashMap<>();
fixed

2022-11-30 17:23 UTC, AlexanderSharygin commented on src/main/java/ru/practicum/shareit/item/ItemDaoImpl.java
> +                .findFirst().get();
fixed

2022-11-30 17:28 UTC, AlexanderSharygin commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +    public UserDto findById(long id) {
fixed

2022-11-30 18:01 UTC, AlexanderSharygin commented on src/main/java/ru/practicum/shareit/dao/Dao.java
> +    Optional<T> create(T value);
fixed

2022-11-30 18:17 UTC, AlexanderSharygin commented on src/main/resources/application.properties
>  spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL10Dialect
fixed

2022-12-01 17:29 UTC, FanaticFiz approved these changes

2022-12-01 17:29 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/ItemDaoImpl.java
> +        Item existedItem = items.values().stream()
Смотри, `findFirst` возвращает `Optional`, а у того в свою очередь есть метод `orElseThrow`... в итоге код должен выглядеть так.

```
        Item existedItem = items.values().stream()
                .filter(k -> k.getId().equals(item.getId()))
                .findFirst().orElseThrow(() -> new NotFoundException("Item with id " + item.getId() + " is not found"));
```

Это наиболее частый приём, запоминай...

2022-12-01 17:29 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +        User user = userDao.findById(id)
Вот еще пример, как сейчас принято писать

```
        return userDao.findById(id)
                      .map(UserMapper::toUserDto)
                      .orElseThrow(() -> new NotFoundException("User with id " + id + " not exists in the DB"));
```

Т.е. если значение есть то мы его перемапим в dto и вернём, иначе кинем ексепшн.

2022-12-02 16:09 UTC, AlexanderSharygin commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +        User user = userDao.findById(id)
fixed

2022-12-02 16:18 UTC, merged