Add bookings
AlexanderSharygin/java-shareit pull request #2
Opened 2022-12-13 20:03 UTC by AlexanderSharygin

2022-12-13 20:19 UTC, AlexanderSharygin commented
Привет. К сожалению я не смог победить запуск в гитхабе.
Вижу вот такой эксепшен и не знаю что с этим делать
![image](https://user-images.githubusercontent.com/52005798/207435339-1ba51421-ba36-4360-b2c6-6263e54d5948.png)

2022-12-13 20:20 UTC, AlexanderSharygin commented
Так же мне не удалось настроить двустронний мапинг в ргиуктфеу между итемами и комментариями - перепробовал кучу решений но так ничего и не получилось( мне нужна помощьв этих двух вопросах

2022-12-14 15:44 UTC, AlexanderSharygin commented
> 

Ну насчет двустороннего мапинга вижу во что написано в аздании:
![image](https://user-images.githubusercontent.com/52005798/207641396-b89ea431-d105-4b1f-996e-ee809a05d24a.png)
так что кажется вопрос снят

2022-12-14 18:04 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2022-12-14 18:04 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +    List<Item> findByNameContainingIgnoreCaseOrDescriptionContainingIgnoreCaseAndAvailableIsTrue(
Длинна названия метода на грани можно сказать!
Это хорошо для прототепирования, но когда приходиться писать вот такое то лучше заменить на самописный query

2022-12-14 18:04 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +        List<User> users = repository.findAll();
Во первых можно сразу return
А во вторых переноси методы в цепочках на новую строку обязательно!
Даже если помещается в одну строку, это выделяет те действия что мы выполнили.

```
    public List<UserDto> getAll() {
        return repository.findAll().stream()
                         .map(UserMapper::toUserDto)
                         .collect(Collectors.toList());
    }
```

2022-12-14 19:52 UTC, AlexanderSharygin commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +        List<User> users = repository.findAll();
fixed

2022-12-14 20:12 UTC, AlexanderSharygin commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +    List<Item> findByNameContainingIgnoreCaseOrDescriptionContainingIgnoreCaseAndAvailableIsTrue(
Fixed

2022-12-15 15:53 UTC, AlexanderSharygin commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        for (ItemDto itemDto : result) {
Fixed

2022-12-15 19:07 UTC, FanaticFiz approved these changes

2022-12-20 16:59 UTC, merged